name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-11 libgtest-dev
        cd /usr/src/gtest
        sudo cmake -DCMAKE_CXX_STANDARD=14 .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Build main program
      run: make all CXX=g++-11

    - name: Build and run C++ tests
      run: make run_tests CXX=g++-11 

    - name: Run Python tests
      run: |
        cd tests
        chmod +x simple_test.py run_all_tests.py
        ./run_all_tests.py 